# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true
permalink:          "/:title"
highlighter:        pygments
timezone:           America/Denver

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Do not copy these file to the output directory
exclude:            [ README.md ]

# Setup
title:               Nathan Bellowe
tagline:             How's it going?
url:                 "http://nbellowe.github.io"
paginate:            4

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nathan Bellowe
  email:             nbellowe@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/nbellowe/nbellowe

# Conversion
markdown:    redcarpet
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes"]

kramdown:
  auto_ids: true

pages_list:
  Home: '/index.html'
  About: '/about.html'
  Tags: '/tags.html'
  Feed: '/atom.xml'

gems:
    - jekyll-redirect-from


#picture:
#  source: "assets/imgs/_fullsize"
#  output: "generated"
#  markup: "picture"

# Image settings
#image_base:          /public/images/
