# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true
permalink:          "/:title"
highlighter:        pygments
timezone:           America/Denver

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Do not copy these file to the output directory
exclude:            [ .gitignore, .gitmodules, CNAME, README.md, fractal/FractalExplorer/ ]

# Setup
title:               Nathan Bellowe
tagline:             My personal website.
url:                 "http://nbellowe.github.io"
paginate:            4

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nathan Bellowe
  email:             nbellowe@gmail.com

pages_list:
  Home: '/index.html'
  About: '/about.html'
  Tags: '/tags.html'

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/nbellowe/nbellowe

# Conversion
markdown:    redcarpet
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes"]

kramdown:
  auto_ids: true

gems:
    - jekyll-redirect-from
    - jekyll-feed
    - jekyll-sitemap
